# Generated by Django 4.0.6 on 2022-07-18 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名')),
                ('sort', models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='言語名称')),
                ('code', models.CharField(max_length=20, verbose_name='言語コード')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '言語',
                'verbose_name_plural': '言語',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名')),
                ('sort', models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション')),
                ('keywords', models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名称')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名')),
                ('sort', models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション')),
                ('keywords', models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名称')),
                ('category_type', models.IntegerField(choices=[(1, 'カテゴリー'), (2, 'シリーズ')], verbose_name='カテゴリータイプ')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='親カテゴリー')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名')),
                ('sort', models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション')),
                ('keywords', models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード')),
                ('title', models.CharField(max_length=250, verbose_name='タイトル')),
                ('overview', models.CharField(blank=True, max_length=500, null=True, verbose_name='概要')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload', verbose_name='ファイル')),
                ('published_at', models.DateTimeField(blank=True, help_text='未来の時間を設定した場合に、予約公開になる。', null=True, verbose_name='公開日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='カテゴリー')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='タグ')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('sort',),
            },
        ),
    ]
