# Generated by Django 4.0.6 on 2022-07-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('sort',), 'verbose_name': '言語', 'verbose_name_plural': '言語'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('sort',), 'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.AlterField(
            model_name='article',
            name='alias',
            field=models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort',
            field=models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード'),
        ),
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AlterField(
            model_name='language',
            name='alias',
            field=models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=20, verbose_name='言語コード'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, verbose_name='言語名称'),
        ),
        migrations.AlterField(
            model_name='language',
            name='sort',
            field=models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート'),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='alias',
            field=models.SlugField(blank=True, help_text='URL でアクセスする時に使用する識別子', null=True, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, help_text='最大120文字まで入力できる。', max_length=120, null=True, verbose_name='メタディスクリプション'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keywords',
            field=models.CharField(blank=True, help_text='5つを目安として入力する。', max_length=200, null=True, verbose_name='メタキーワード'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.language', verbose_name='言語'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='タグ名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort',
            field=models.IntegerField(default=0, help_text='値の若い順で表示される。', verbose_name='ソート'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
    ]
